[[redirects]]
  from = "/pure-ui"
  to = "https://docs.google.com/presentation/d/e/2PACX-1vQA0KRcuTMHeX5q15iq1J6Oagv0oSqZf44mhgHjzGt5dRO-j0n_vrm_bmsK7xdLHSdbdwx9_07Z76lC/pub?start=false&loop=false&delayms=5000"
  status = 200
  force = true
